name: "CI"
on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.org'
    - '.dir-locals.el'
    branches:
      - master
  push:
    paths-ignore:
    - '**.md'
    - '**.org'
    - '.dir-locals.el'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - snapshot

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2

    - name: Check emacs version
      run: emacs --version

    - name: Test
      run: make test
